### ISSUE TITLE
Missing legend in the plot of Logistic Regression

### ISSUE THREAD

**Issue by nguyenvulong** [GokuMohandas/Made-With-ML#229]
**Problem:** only `malignant` legend was shown ( `plot data` section of the [Logistic Regression](https://madewithml.com/courses/foundations/logistic-regression/) lesson.)
![image](https://user-images.githubusercontent.com/1311412/236676696-e0bc6e75-892c-427a-a5ed-12c619d609e0.png)

**Fix**
I am not sure if I should create a PR for a notebook ... so I created this issue with a working code instead. Please see below

```
# Define X and y
X = df[["leukocyte_count", "blood_pressure"]].values
y = df["tumor_class"].values

# Split the data into separate arrays for benign and malignant classes
X_benign = X[y == "benign"]
X_malignant = X[y == "malignant"]

# Plot the data for each class separately
fig, ax = plt.subplots()
ax.scatter(X_benign[:, 0], X_benign[:, 1], c="blue", s=25, edgecolors="k", label="benign")
ax.scatter(X_malignant[:, 0], X_malignant[:, 1], c="red", s=25, edgecolors="k", label="malignant")
ax.set_xlabel("leukocyte count")
ax.set_ylabel("blood pressure")
ax.legend(loc="upper right")
plt.show()
```

**Comment by ShathishWarmaS** [comment]
Both are showing 
<img width="1440" alt="Screenshot 1945-03-05 at 1 45 54 PM" src="https://github.com/GokuMohandas/Made-With-ML/assets/103341418/0b7e0c51-87ee-4724-8de6-18a1e1365271">

# Plot the data for each class separately
fig, ax = plt.subplots()
ax.scatter(X_benign[:, 0], X_benign[:, 1], c="blue", s=25, edgecolors="k", label="benign")
ax.scatter(X_malignant[:, 0], X_malignant[:, 1], c="red", s=25, edgecolors="k", label="malignant")
ax.set_xlabel("leukocyte count")
ax.set_ylabel("blood pressure")
ax.legend(loc="upper right")
plt.show()

**Comment by yuboona** [comment]
您的邮件我已收到，将尽快回复！！
