### ISSUE TITLE
"Product Design" page text cut-off

### ISSUE THREAD

**Issue by emmyscode** [GokuMohandas/Made-With-ML#231]
I'm look at the [Product Design](https://madewithml.com/courses/mlops/product-design/) page, and I'm seeing two small errors:

1. Small typo in the "Value Proposition" section
> `product`: what needs to be **build** to help our users reach their goals?
2. The article stops abruptly mid-sentence, see below
<img width="794" alt="Screenshot 2023-07-26 at 11 20 45 AM" src="https://github.com/GokuMohandas/Made-With-ML/assets/78717839/6d891b1d-b565-4005-b225-605863e22d4f">

**Comment by GokuMohandas** [comment]
Fixed, thanks @emmyscode! There will likely be more -- wish VSCode had a Google docs type of grammar/language checker.
