### ISSUE TITLE
Serving from Old course

### ISSUE THREAD

**Issue by Morse2580** [GokuMohandas/Made-With-ML#234]
Hello, I appreciate your content and find it really comprehensive. Could you please upload a the serving section from the old course (FAST API).

**Comment by innat** [comment]
@GokuMohandas 
If possible, please host the removed contents somewhere else. Old is Gold. ;)

**Comment by GokuMohandas** [comment]
Hi @Morse2580 and @innat, you can find them here:

Foundation lessons: https://madewithml.com/courses/foundations/ (also at the top tabs)
Serving with FastAPI: https://madewithml.com/courses/mlops/api/

**Comment by arogyakoirala** [comment]
I saw this is already closed but just in case anyone else lands here looking for old content, you can use the Wayback Machine to view an archived version of the site: https://web.archive.org/web/20221201110239/https://madewithml.com/courses/mlops/packaging/
